localstack:
  host: localhost

cloud:
  aws:
    credentials:
      access-key: foo
      secret-key: bar
    sqs:
      order-queue:
        url: http://localhost:4566/000000000000/order-queue
        name: order-queue
      order-queue-2:
        url: http://localhost:4566/000000000000/order-queue-2
        name: order-queue-2
    sns:
      order-created:
        arn: arn:aws:sns:eu-central-1:000000000000:order-created-topic
        name: order-created-topic
    stack:
      auto: false
    region:
      static: eu-central-1
